arch:
  - ard64
  - ppc64le
  - s390x
branches:
  only:
    - master
language: node_js
env:
  NODE_OPTIONS: --max-old-space-size=4096
node_js:
  - '10'
  - '12'
  - '14'
  - '16'
before_install: npm install -g npm
script:
  - npm run --ignore-scripts build
  - npm test --ignore-scripts
