arch:
  - arm64
  - ppc64le
  - s390x
branches:
  only:
    - master
language: node_js
node_js:
  - 10
  - 12
  - 14
  - 16
before_install: |
  NODEJS_VERSION=$(node --version)
  if [ 'v10' == ${NODEJS_VERSION%%.*} ]
  then
    npm install --global npm@7
  else
    npm install --global npm@8
  fi
script:
  - npm run --ignore-scripts build
  - npm test --ignore-scripts
