arch:
  - arm64
  - ppc64le
  - s390x
branches:
  only:
    - master
language: node_js
node_js:
  - 10
  - 12
  - 14
  - 16
before_install: npm install --global npm
script:
  - npm run --ignore-scripts build
  - npm test --ignore-scripts
